module.exports = {
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: "#8D6749",
        secondary: "#4E5D45",
        accent: "#CBAF7A",
        background: "#F6F1EC",
        error: "#E76D62",
        success: "#22C55E",
        warning: "#FACC15",
        card: "#FFFFFF",
        sidebar: "#18181B",
        border: "#E5E7EB",
        muted: "#9CA3AF",
        heading: "#1E293B",
        link: "#2563EB",
        overlay: "rgba(0,0,0,0.1)",
        darkGreen: "#004030",
        mediumGreen: "#4A9782",
        softYellow: "#DCD0A8",
        lightCream: "#FFF9E5",
      },
      borderColor: {
        darkGreen: "#004030",
        mediumGreen: "#4A9782",
        softYellow: "#DCD0A8",
        lightCream: "#FFF9E5",
      },
      boxShadow: {
        darkGreen: "0 4px 6px -1px #004030, 0 2px 4px -1px #004030",
        mediumGreen: "0 4px 6px -1px #4A9782, 0 2px 4px -1px #4A9782",
        softYellow: "0 4px 6px -1px #DCD0A8, 0 2px 4px -1px #DCD0A8",
        lightCream: "0 4px 6px -1px #FFF9E5, 0 2px 4px -1px #FFF9E5",
      },
      textUnderlineOffset: {
        darkGreen: '3px',
        mediumGreen: '3px',
        softYellow: '3px',
        lightCream: '3px',
      },
      backgroundColor: {
        darkGreen: "#004030",
        mediumGreen: "#4A9782",
        softYellow: "#DCD0A8",
        lightCream: "#FFF9E5",
      },
      fontFamily: {
        openSans: ['"Tajawal"', "Arial", "Helvetica", "sans-serif"],
        cinzel: ['"Cinzel"', "serif"],
        archivo: ['"Archivo"', "sans-serif"],
        inter: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [require('tailwind-scrollbar')],
};